openapi: 3.0.1
info:
  title: Delilah Restó
  description: Backend para un sistema de pedidos online para un restaurante poniendo
    en funcionamiento las partes necesarias para montar una REST API que permita realizar
    operaciones CRUD sobre una estructura de datos.
  termsOfService: http://swagger.io/terms/
  contact:
    email: juniiormediina@gmail.com
  license:
    name: MIT
    url: https://github.com/juniiormediina/DelilahResto/blob/master/LICENSE
  version: 1.0.0
servers:
- url: http://localhost:3000/api
tags:
- name: Create User
  description: Everything about your Pets
- name: Login User
  description: Access to Petstore orders
- name: Create Product
  description: Operations about user
- name: Find Products by ID
  description: Operations about user
- name: Update Products by ID
  description: Operations about user
- name: Delete Products by ID
  description: Operations about user
- name: Get Products
  description: Operations about user
- name: Create Request
  description: Operations about user
- name: Find Requests by ID
  description: Operations about user
- name: Update Requests by ID
  description: Operations about user
- name: Delete Requests by ID
  description: Operations about user
- name: Get Requests
  description: Operations about user
- name: Get Orders
  description: Operations about user
paths:
  /users/singup:
    post:
      tags:
      - Create User
      summary: Creación y registro de usuarios
      operationId: addUser
      requestBody:
        description: Datos del usuario a registrar
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Create_User'
        required: true
      responses:
        200:
          description: Gives us as an answer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Create_User' 
        400:
          description: The email already exists
        406:
          description: Please fill all fields
        500:
          description: Sorry, the server has presented an error. Try again later
      security:
      - bearerAuth: []
  /users/signin:
    post:
      tags:
      - Login User
      summary: Enter the registered email and password
      operationId: loginUser
      requestBody:
        description: Enter the registered email and password
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login_User'
        required: true
      responses:
        200:
          description: It returns the user access JWT
          content:
            application/json:
              schema:
                example: '"yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiSnVuaW9yIiwibGFzdG5hbWUiOiJNZWRpbmEiLCJwaG9uZSI6IjMxNzI5MjIyNzUiLCJhZGRyZXNzIjoiY2wgMSAjIDIgLSAzMCIsImVtWlsIjoianVuaW9yQGdtYWlsLmNvbSIsInBhc3MiOiIxMjM0Iiwicm9sIjoiYWRtaW4iLCJpYXQiOjE2MDQwMjkzNzJ9.Xcpmu_WqlUsr1DXQHt0y0fynDkj7wjTFzpjo78GiDS8asda"'
        400:
          description: the user with the email sent does not exist
        401:
          description: Invalid password or email
        406:
          description: Faltan campos por rellenar, por favor envie todos los campos
            requeridos
      security:
      - bearerAuth: []
  /products/createProducts:
    post:
      tags:
      - Create Product
      summary: Create a new product
      operationId: createProduct
      requestBody:
        description: Enter the required data to create a product
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Create_Product'
        required: true
      responses:
        200:
          description: It gives us the data of the product created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Create_Product'
        401:
          description: You don't have profiles of administrator to continue with this action
        406:
          description: Please fill all fields
        500:
          description: Sorry, the server has presented an error. Try again later
      security:
      - bearerAuth: []
  /products/findProducts/{productId}:
    get:
      tags:
      - Find Products by ID
      summary: Find pet by ID
      operationId: FindPoductsById
      parameters:
      - name: productId
        in: path
        description: ID of product to find
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Answer an object with the data of the searched product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Create_Product'
        404:
          description: Product not found
      security:
      - bearerAuth: []
  /products/updateProducts/{productId}:
    put:
      tags:
      - Update Products by ID
      summary: Update product by ID
      operationId: updateProduct
      parameters:
      - name: productId
        in: path
        description: ID of product to update
        required: true
        schema:
          type: integer
      requestBody:
        description: Updated user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Update_Product'
        required: true 
      responses:
        200:
          description: The answer is the confirmation that the product has been updated
          content:
            application/json:
              schema:
                example: "Updated product"
        401:
          description: You don't have profiles of administrator to continue with this action
          content: {}
        404:
          description: the product does not exist, please check
        500:
          description: Sorry, the server has presented an error. Try again later
      security:
      - bearerAuth: []
  /products/deletePoducts/{productId}:
    delete:
      tags:
      - Delete Products by ID
      summary: Eliminar un producto por ID
      operationId: deleteProduct
      parameters:
      - name: productId
        in: path
        description: Id del producto a eliminar
        required: true
        schema:
          type: integer
      responses:
        200:
          description: La respuesta es la confirmacion de que el producto ha sido eliminado satisfactoriamente
          content:
            application/json:
              schema:
                example: '"Producto Eliminado"'
        401:
          description: Debes ingresar con tu usuario y contraseña para utilizar este
            servicio
        403:
          description: Debes tener permisos de administrador para realizar esta petición
        404:
          description: Producto no encontrado, por favor verifique
        500:
          description: Sorry, the server has presented an error. Try again later
      security:
      - bearerAuth: []
  /products/productsList:
    get:
      tags:
      - Get Products
      summary: Obtener una lista de los productos registrados
      operationId: getProductList
      responses:
        200:
          description: Consulta exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Create_Product'
        401:
          description: Debes ingresar con tu usuario y contraseña para utilizar este
            servicio
        500:
          description: Error interno
      security:
      - bearerAuth: []
  /request/CreateRequest:
    post:
      tags:
      - Create Request
      summary: Crear un pedido
      operationId: getOrderById
      requestBody:
        description: Es neceario el envio de los datos requeridos
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Create_Request'
        required: true
      responses:
        200:
          description: Nos trae como respuesta el resultado del pedido creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response_Create_Request'
        400:
          description: Usuario no se pudo verificar
        401:
          description: Debes ingresar con tu usuario y contraseña para utilizar este
            servicio
        406:
          description: Campos enviados no válidos
        500:
          description: Sorry, the server has presented an error. Try again later
      security:
      - bearerAuth: []
  /request/findRequest/{requestId}:
    get:
      tags:
      - Find Requests by ID
      summary: Actualizar el estado de un pedido
      operationId: FindRequestById
      parameters:
      - name: requestId
        in: path
        description: Id del pedido a actualizar
        required: true
        schema:
          type: integer
      responses:
        200:
            description: Responde un objeto con los datos del producto buscado
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Create_Request'
        401:
          description: Debes ingresar con tu usuario y contraseña para utilizar este
            servicio
        403:
          description: Debes tener permisos de administrador para realizar esta petición
        404:
          description: Datos no encontrados, no se pudo actualizar tu pedido.
        406:
          description: Campos no validos
        500:
          description: Sorry, the server has presented an error. Try again later
      security:
      - bearerAuth: []
  /request/updateRequest/{requestId}:
    put:
      tags:
      - Update Requests by ID
      summary: Actualizar el estado de un pedido
      operationId: updateRequest
      parameters:
      - name: requestId
        in: path
        description: Id del pedido a actualizar
        required: true
        schema:
          type: integer
      responses:
        200:
          description: La respuesta es la confirmacion de que el pedido ha sido actualizado
          content:
            application/json:
              schema:
                example: "Pedido actualizado"
        401:
          description: Debes ingresar con tu usuario y contraseña para utilizar este
            servicio
        403:
          description: Debes tener permisos de administrador para realizar esta petición
        404:
          description: Datos no encontrados, no se pudo actualizar tu pedido.
        406:
          description: Campos ingresados no validos
        500:
          description: Sorry, the server has presented an error. Try again later
      security:
      - bearerAuth: []
  /request/deleteRequest/{requestId}:
    delete:
      tags:
      - Delete Requests by ID
      summary: Eliminar un pedido por ID
      operationId: deleteRequest
      parameters:
      - name: requestId
        in: path
        description: Id del pedido a eliminar
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Pedido eliminado satisfactoriamente
          content:
            application/json:
              schema:
                example: '"Pedido eliminado"'
        401:
          description: Debes ingresar con tu usuario y contraseña para utilizar este
            servicio
        403:
          description: Debes tener permisos de administrador para realizar esta petición
        404:
          description: Pedido no encontrado, por favor verifique
        500:
          description: Sorry, the server has presented an error. Try again later
      security:
      - bearerAuth: []
  /request/requests:
    get:
      tags:
      - Get Requests
      summary: obtener todos los pedidosrealizados
      operationId: getRequest
      responses:
        200:
          description: Nos responde un objeto que contiene todos los pedidos generados
          content:
            application/json:
              schema:
                type: object
        401:
          description: Debes ingresar con tu usuario y contraseña para utilizar este
            servicio
        500:
          description: Sorry, the server has presented an error. Try again later
      security:
      - bearerAuth: []
  /order/orders:
    get:
      tags:
      - Get Orders
      summary: Logs out current logged in user session
      operationId: logoutUser
      responses:
        200:
          description: nos responde un objeto con todos las ordenes generadas
          content:
            application/json:
              schema:
                type: object
        401:
          description: Debes ingresar con tu usuario y contraseña para utilizar este
            servicio
        500:
          description: Sorry, the server has presented an error. Try again later
      security:
      - bearerAuth: []
components:
  schemas:
    Create_User:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
        phone:
          type: string
        address:
          type: string
        email:
          type: string
        password:
          type: string
        profile:
          type: string
    Login_User:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    Create_Request:
      type: object
      properties:
        payment_method:
          type: string
        products:
          type: array
          items:
            type: object
            properties:
              productId:
                type: integer
              quantity:
                type: integer
        userId:
          type: integer
    Response_Create_Request:
      type: object
      properties:
        id:
          type: integer
        Payment_method:
          type: string
        userId:
          type: integer
        status:
          type: integer
        updatedAt:
          type: string
        createdAt:
          type: string
    Create_Product:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        type:
          type: string
        price:
          type: string
        image:
          type: string
    Update_Product:
      type: object
      properties:
        price:
          type: string 
          
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
